### ISSUE TITLE
Integrate into main repo

### ISSUE THREAD

**Issue by multimeric** [MainRo/docker-deepspeech-server#3]
The normal convention with Dockerfiles is to put them in the root directory of the main project. Perhaps this should be done here?

**Comment by MainRo** [comment]
Keeping the docker configuration in the project's repo has the advantage of being able to publish the docker image for each tag of the python package. But on the other side it also means that the docker packaging clutters the history of the python repo.
I would prefer to keep it separate, but I must admit that I should update this repo accordingly so that there is a new image published on docker-hub each time I publish a new version of deepspeech-server.

**Comment by multimeric** [comment]
That would be another benefit of putting them in the same repo. You could have a Travis build for the repo that triggers whenever you push to master, which builds and pushes the image to Docker Hub.

**Comment by MainRo** [comment]
from what I see, most projects keep the docker packaging independent from the project itself. Here are some examples:

- vernemq: https://github.com/vernemq/docker-vernemq
- consul: https://github.com/hashicorp/docker-consul
- cpython: https://github.com/docker-library/python

Concerning the automated builds, I already configured it on docker hub some time ago:
https://hub.docker.com/r/romainsah/deepspeech-server/

The main point here I think, is the fact I did not update this repo when releasing deepspeech-server. I will took some time to update this repo accordingly :D 

So for now I prefer to keep the docker packaging in a separate repository.
